version: "3.7"
services: 
  mysql-db:
    container_name: mydb
    build:
      context: ./db
    image: uopsdod/mysql-db-01
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
